import Head from 'next/head';
import { BsFillMoonStarsFill, BsTwitter, BsFacebook, BsGithub } from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Peri Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-rice-color px-10 md:px-20 lg:px-40'>
        {' '}
        <section className='min-h-screen'>
          <nav className='sticky top-0 py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-Zcool'>Peri Portfolio</h1>
            <h2>About</h2>
            <h2>Projects</h2>
            <h2>Contact</h2>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer' />
              </li>
              <li>
                <a
                  className='bg-gradient-to-r from-cyan-500 to-cyan-300 text-white px-4 py-2 rounded-md ml-8'
                  href='#'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-cyan-600 font-medium'>Peri Lin</h2>
            <h3 className='text-2xl py-2'>Web Developer</h3>
            <p className='text-md py-5 leading-7 text-gray-700'>
              Developer providing sevices for programming needs. Contact me down below and let's get
              cracking!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-14 py-3 text-gray-400'>
            <BsTwitter />
            <BsFacebook />
            <BsGithub />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-orange-400 rounded-full h-80 w-80'>
            {/* Avatar */}
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>技術 Skills</h3>
            <p>react, Next.js, Node.js....</p>
          </div>
          {/* Cards */}
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <h3 className='text-lg'>
              <p className='py-2'>description....</p>
            </h3>
          </div>
        </section>
      </main>

      <footer className='flex justify-center'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by <span>peri</span>
        </a>
      </footer>
    </div>
  );
}
