import Head from 'next/head';
import { BsFillMoonStarsFill, BsTwitter, BsFacebook, BsGithub } from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Peri Lin Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-rice-color px-10 md:px-16 lg:px-32'>
        <section className='min-h-screen'>
          <nav className='sticky top-0 py-10 mb-12 flex justify-between items-center'>
            <div className='px-4 py-2  align-middle'>
              <a className='text-xl font-Zcool'>Peri Portfolio</a>
            </div>
            <div className='flex justify-between align-middle'>
              <a className='text-l font-Zcool px-4 py-2'>About</a>
              <a className='text-l font-Zcool px-4 py-2'>Projects</a>
              <a className='text-l font-Zcool px-4 py-2'>Contact</a>
              <button className='cursor-pointer px-4 py-2'>
                <BsFillMoonStarsFill />
              </button>
              <a className='bg-gray-color text-white px-4 py-2 rounded-full' href='#'>
                <span>Resume</span>
              </a>
            </div>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-gray-color font-medium'>Peri Lin</h2>
            <h3 className='text-2xl py-2'>Web Developer</h3>
            <p className='text-md py-5 leading-7 text-gray-700'>
              Developer providing sevices for programming needs. Contact me down below and let's get
              cracking!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-14 py-3 text-gray-400'>
            <BsTwitter />
            <BsFacebook />
            <BsGithub />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-lemon-color rounded-full h-80 w-80'>
            {/* Avatar */}
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>技術 Skills</h3>
            <p>React, Next.js, Node.js....</p>
          </div>
          {/* Cards */}
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <h3 className='text-lg'>
              <p className='py-2'>description....</p>
            </h3>
          </div>
        </section>
      </main>

      <footer className='flex justify-center'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by <span>PeriYumYum</span>
        </a>
      </footer>
    </div>
  );
}
